
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES

	('provision_coin_1787_cent_tkn', 'Feather', 1, 0, 1),
	('provision_coin_1789_pny', 'Feather', 1, 0, 1),
	('provision_coin_1792_lib_qtr', 'Feather', 1, 0, 1),
	('provision_coin_1792_nickel', 'Feather', 1, 0, 1),
	('provision_coin_1792_qtr', 'Feather', 1, 0, 1),
	('provision_coin_1794_slv_dlr', 'Feather', 1, 0, 1),
	('provision_coin_1795_hlf_eag', 'Feather', 1, 0, 1),
	('provision_coin_1796_hlf_pny', 'Feather', 1, 0, 1),
	('provision_coin_1798_slv_dlr', 'Feather', 1, 0, 1),
	('provision_coin_1800_five_dlr', 'Feather', 1, 0, 1),
	('provision_coin_1800_gld_dlr', 'Feather', 1, 0, 1),
	('provision_coin_1800_gld_qtr', 'Feather', 1, 0, 1),
	('provision_coin_1800_hlf_dime', 'Feather', 1, 0, 1),
	('provision_feather', 'Feather', 1, 0, 1),
	('provision_generic_key', 'Gold Ring', 1, 0, 1),
	('provision_goldtooth', 'Gold Nugget', 1, 0, 1),
	('provision_gold_earring', 'Gold Nugget', 1, 0, 1),
	('provision_gold_necklace', 'Gold Nugget', 1, 0, 1),
	('provision_gold_nugget', 'Gold Nugget', 1, 0, 1),
	('provision_gold_ring', 'Gold Ring', 1, 0, 1),
	('provision_shark_tooth', 'Shark Tooth', 1, 0, 1),
	('provision_silvertooth', 'Gold Nugget', 1, 0, 1),
	('provision_silver_earring', 'Gold Nugget', 1, 0, 1),
	('provision_silver_necklace', 'Gold Nugget', 1, 0, 1),
	('provision_silver_nugget', 'Silver Nugget', 1, 0, 1),
	('provision_silver_ring', 'Gold Ring', 1, 0, 1);

